### ISSUE TITLE
Lowering gas costs epic

### ISSUE THREAD

**Issue by TimDaub** [whitecube-online/balot#22]
- Current `[PASS] testRunSafeMint() (gas: 15707183)`
- [x] ask L if we can shorten the URI component by removing the file type extension
- [ ] What transaction gas size can we possibly send to mainnet? Is 15M realistic?
- [ ] Seek answer to: https://github.com/whitecube-online/balot/issues/26
- [x] https://github.com/whitecube-online/balot/issues/29

**Comment by lajarre** [comment]
>  What transaction gas size can we possibly send to mainnet? Is 15M realistic?

A quick calculation I'm not 100% confident about, using 300 minting iterations:

```yaml
# see https://github.com/whitecube-online/balot/issues/29#issuecomment-1143735686
gas needed: 16 500 000
# see https://ethereumprice.org/gas/
best weekly gas price: 10 gwei
total gas cost: gas needed * best weekly gas price
```

we have thus `total gas cost` at 165 10^6 gwei, or 0.165 ETH. Which is nearly 300$ by current prices.
